### ISSUE TITLE
二进制文件运行方式，windows amd64版本运行有问题

### ISSUE THREAD

**Issue by LIGHT1213** [ConnectAI-E/Dingtalk-OpenAI#243]
powershell使用命令`.\chatgpt-dingtalk.exe`运行后报错，日志如下
```bash
[signal 0xc0000005 code=0x0 addr=0x48 pc=0xbef76f]

goroutine 1 [running]:
github.com/charmbracelet/log.(*Logger).log(0x8?, 0x862fd60?, {0x12fbb20?, 0xc0034eaf00?}, {0x0?, 0x131e940?, 0xc00862fd01?})
        /go/pkg/mod/github.com/charmbracelet/log@v0.2.1/logger.go:52 +0x4f
github.com/charmbracelet/log.(*Logger).Fatal(0xc004a2a8a0?, {0x12fbb20?, 0xc0034eaf00?}, {0x0?, 0x22c5da63700?, 0xc000057de0?})
        /go/pkg/mod/github.com/charmbracelet/log@v0.2.1/logger.go:318 +0x3c
github.com/eryajf/chatgpt-dingtalk/pkg/logger.Fatal(...)
        /github/workspace/pkg/logger/logger.go:41
github.com/eryajf/chatgpt-dingtalk/config.LoadConfig()
        /github/workspace/config/config.go:244 +0x276
github.com/eryajf/chatgpt-dingtalk/public.InitSvc()
        /github/workspace/public/public.go:20 +0x1d
main.init.0()
        /github/workspace/main.go:23 +0x19
```

**Comment by LIGHT1213** [comment]
还有在docker运行也有两个问题

1. 容器创建命令中关于`DINGTALK_CREDENTIALS`没有详细说明是什么。当然可以从其他的地方知道他和CREDENTIALS是一个

**Comment by eryajf** [comment]
> 还有在docker运行也有两个问题
> 
> 1. 容器创建命令中关于`DINGTALK_CREDENTIALS`没有详细说明是什么。当然可以从其他的地方知道他和CREDENTIALS是一个


```
# 钉钉应用鉴权凭据信息，支持多个应用。通过请求时候鉴权来识别是来自哪个机器人应用的消息
# 设置credentials 之后，即具备了访问钉钉平台绝大部分 OpenAPI 的能力；例如上传图片到钉钉平台，提升图片体验，结合 Stream 模式简化服务部署
# client_id 对应钉钉平台 AppKey/SuiteKey；client_secret 对应 AppSecret/SuiteSecret
credentials:
  -
    client_id: "put-your-client-id-here"
    client_secret: "put-your-client-secret-here"
```
